### ISSUE TITLE
Proposal: configuration file

### ISSUE THREAD

**Issue by ghost** [drradao/laravel-bard#13]
Hi,
Thanks A LOT for this package, which is what I had been searching for so long!

Could you consider adding a configuration file to allow user to choose precisely in which directories files should be created ?

For instance, if in a Laravel app Models are obviously found in `app/Models`, in a package, they could logically be placed in `src/Database/Models` directory, along with other files related to database (Scopes, traits, etc.).

The configuration file would be a simple mapping like:

```
return [
    'models' => 'src/Database/Models',
    'providers' => 'src/Providers,
   // etc.
]
```
Provided values would simply override defaults.

It could be something like `.bard.config.php` in the package root (and added to `.gitignore`).

**Comment by drradao** [comment]
Hi!

Thank you, it's poorly maintained but gets the job done.

I'm really fond of patterns so when I created it I've tried for it to follow the [Directory Structure of Laravel](https://laravel.com/docs/11.x/structure) slightly adapted to packages.

That means that your Laravel Models should be placed in `src/Models`, leaving the `database` folder for migrations, factories and seeders.

Is bard behaving the way I've described? Do you still feel it's a needed feature?

**Comment by ghost** [comment]
Hi, thanks for your answer.

I understand your position, but a package does not always have the same structure as the application... `laravel/laravel` is not a library (unlinke `laravel/framework` which does not have the same files layout), therefore the structure is specific to an application.

I've seen in many packages a directory structure like, for example:

```
src/Database/Models/
src/Database/Scopes/
src/Database/Factories/
...
src/Http/Requests/
src/Http/Controllers/
...
stubs/migrations/
stubs/config/
```

There is not absolute rule, everyone has their own preferences which may depend on the package itself (a package which has only database-related classes may not have an `src/Database` directory since it would be the only one).

I think it would be really valuable to allow users to specify directories according to their own criteria/requirements.

**Comment by drradao** [comment]
I may consider adding it in the future, this package has been developed and updated on a need basis. Sorry it's not the answer you wanted to hear.
